server:
  port: 8081

spring:
  application:
    name: zone-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:mysql://localhost:3306/agms_zone_db?createDatabaseIfNotExist=true # ඔයාගේ DB එකේ නම
    username: root
    password: Thamidu1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/