server:
  port: 8888 # Config Server ?? ???????????? ??????? 8888 port ???

spring:
  application:
    name: config-server
  profiles:
    active: native # Local folder ???? ???????? ??? ???? "native" ??? ??? ??????
  cloud:
    config:
      server:
        native:
          # Settings files ????? folder ??? path ?? ????? ?????
          search-locations: file:/D:/AD2/AGMS-System/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/