server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/D:/AD2/AGMS-System/config-repo
  datasource:
    url: jdbc:mysql://localhost:3306/agms_zone_db?createDatabaseIfNotExist=true # ඔයාගේ DB එකේ නම
    username: root
    password: Thamidu1234
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/